# optimizer info
optimizer:
  name: Adam
  kwargs:
    lr: 0.0002
  other:
    emb_func: 0.0002
    lr_mul: 25
    # emb_func: 0.001 # define lr OR
    # another_part:    # define multi params
    #   lr: 0.1
    #   weight_decay: 0.5


# lr_scheduler info
lr_scheduler:
  name: cosine
  kwargs:
    gamma: 0.5

warmup: 0 # set 0 to turn off warmup
