# optimizer info
optimizer:
  name: Adam
  kwargs:
    lr: 0.0002
  other: ~
    # emb_func: 0.001 # define lr OR
    # another_part:    # define multi params
    #   lr: 0.1
    #   weight_decay: 0.5


# lr_scheduler info
lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 200
    eta_min: 0.00001

warmup: 0 # set 0 to turn off warmup
